Participating rides
AlasDiablo/Rs-Rl-Ld-PPIL pull request #30
Opened 2021-04-10 15:02 UTC by LabaletteMatthieu

Modification index.php et navBar pour différencier trajets créée et ceux aprticipés

2021-04-10 16:07 UTC, AlasDiablo requested changes

2021-04-10 16:07 UTC, AlasDiablo commented on index.php
> +$app->get('/accounts/participating-rides', function (Request $request, Response $response, $args) {
J'ai changé `accounts` par `account`

2021-04-10 16:07 UTC, AlasDiablo commented on src/controller/ListController.php
> +        $rides = Utilisateur::where("email", '=', $_SESSION['mail'])->first()->mesParticipation()->get();
N'oublie pas de verifier si `$_SESSION['mail']` et vide ou non

2021-04-10 17:38 UTC, LabaletteMatthieu commented on src/controller/ListController.php
> +        $rides = Utilisateur::where("email", '=', $_SESSION['mail'])->first()->mesParticipation()->get();
Normalement, tu a pas accès au liens si t'es pas connecté, donc pas besoins de vérifier si ?

2021-04-10 17:39 UTC, AlasDiablo commented on src/controller/ListController.php
> +        $rides = Utilisateur::where("email", '=', $_SESSION['mail'])->first()->mesParticipation()->get();
Tu peut y accédé si tu connais l'url donc avoir des truc qui sont pas sensé s'affiché...

2021-04-12 17:27 UTC, AlasDiablo commented
Je vais faire les changement

2021-04-12 17:30 UTC, merged